#!/bin/bash
# This is a script to setup gym and customized environments
# by J.R. Carneiro
git clone https://github.com/openai/gym
cd gym
pip install -e .
cd ..
cd ContinuousDeepRobot-v0
pip install -e
